window.TETUTI_PRODUCTS = [
  {
    id: "nasi-liwet",
    name: "Nasi Liwet Komplit",
    category: "paket",
    price: 35000,
    badge: "Favorit",
    desc: "Nasi gurih, ayam suwir, telur, teri, dan sambal terasi.",
    image: "assets/nasi-liwet.jpg",
  },
  {
    id: "nasi-box-ayam",
    name: "Nasi Box Ayam Lengkuas",
    category: "paket",
    price: 32000,
    desc: "Nasi putih, ayam goreng lengkuas, tumis buncis, dan sambal.",
    image: "assets/nasi-box.jpg",
  },
  {
    id: "nasi-kuning",
    name: "Nasi Kuning Mini",
    category: "paket",
    price: 28000,
    desc: "Nasi kuning wangi, ayam goreng, telur, dan kering tempe.",
    image: "assets/nasi-kuning.jpg",
  },
  {
    id: "nasi-goreng",
    name: "Nasi Goreng Kampung",
    category: "nasi",
    price: 27000,
    badge: "Pedas pas",
    desc: "Nasi goreng bumbu terasi, telur ceplok, dan kerupuk.",
    image: "assets/nasi-goreng.jpg",
  },
  {
    id: "ayam-bakar",
    name: "Ayam Bakar Madu",
    category: "lauk",
    price: 30000,
    desc: "Paha ayam bakar oles madu, lalapan, dan sambal kecap.",
    image: "assets/ayam-bakar.jpg",
  },
  {
    id: "rendang",
    name: "Rendang Sapi",
    category: "lauk",
    price: 42000,
    badge: "Slow cook",
    desc: "Daging sapi empuk, bumbu rendang pekat, porsi lauk.",
    image: "assets/rendang.jpg",
  },
  {
    id: "ayam-goreng",
    name: "Ayam Goreng Lengkuas",
    category: "lauk",
    price: 28000,
    desc: "Ayam goreng rempah, serundeng lengkuas, dan sambal.",
    image: "assets/ayam-goreng.jpg",
  },
  {
    id: "sate-ayam",
    name: "Sate Ayam 10 Tusuk",
    category: "lauk",
    price: 30000,
    desc: "Sate ayam bumbu kacang, lontong, dan bawang goreng.",
    image: "assets/sate.jpg",
  },
  {
    id: "gado-gado",
    name: "Gado-gado Siram",
    category: "sayur",
    price: 25000,
    desc: "Sayur rebus, tahu, tempe, lontong, bumbu kacang kental.",
    image: "assets/gado.jpg",
  },
  {
    id: "soto-ayam",
    name: "Soto Ayam",
    category: "nasi",
    price: 26000,
    desc: "Kuah kuning, suwiran ayam, soun, telur, dan nasi.",
    image: "assets/soto.jpg",
  },
  {
    id: "es-teh",
    name: "Es Teh Manis",
    category: "minuman",
    price: 8000,
    desc: "Teh manis dingin, segar buat dampingi makan.",
    image: "assets/es-teh.jpg",
  },
  {
    id: "es-jeruk",
    name: "Es Jeruk Peras",
    category: "minuman",
    price: 12000,
    desc: "Jeruk peras murni, bisa request kurang manis.",
    image: "assets/es-jeruk.jpg",
  },
];
