window.TETUTI_PRODUCTS = [
  {
    id: "sambal-crispy",
    name: "Sambal Crispy",
    category: "camilan",
    badge: "Best seller",
    hook: "Pedas, renyah, nagih!",
    desc: "Bumbu pilihan yang bikin ketagihan. Digoreng garing sampai sempurna, tanpa pengawet dan pewarna buatan.",
    highlights: [
      "Pedas nampol",
      "Renyah maksimal",
      "Teman nasi, bubur, mie, ayam & telur",
    ],
    image: "assets/sambal-crispy.jpg",
  },
  {
    id: "paket-hantaran",
    name: "Paket Hantaran",
    category: "hantaran",
    badge: "Hampers",
    hook: "Lezat, renyah, nagih!",
    desc: "Aneka kue lezat dalam satu paket, kemasan cantik untuk hantaran spesial dan momen penting.",
    highlights: ["Isi beragam", "Kemasan cantik", "Siap saji untuk segala momen"],
    image: "assets/paket-hantaran.jpg",
  },
  {
    id: "nasi-kotak",
    name: "Nasi Kotak",
    category: "catering",
    badge: "Catering",
    hook: "Gurih, lezat, fresh",
    desc: "Porsi puas, lauk melimpah. Cocok untuk acara keluarga, arisan, dan catering.",
    highlights: ["Lauk melimpah", "Bumbu asli, gurih mantap", "Harga ramah, aman di kantong"],
    image: "assets/nasi-kotak.jpg",
  },
];
